# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WP
  # pod “PinterestSDK”, :git => “git@github.com:pinterest/ios-pdk.git”
  pod 'PinterestSDK', '~> 1.0'
  
  pod 'InstagramKit', '~> 3.8'
  
  target 'WPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
